/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.47
 * Generated at: 2020-02-16 00:50:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.memberJoin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class memberJoin2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1579876007573L));
    _jspx_dependants.put("jar:file:/D:/project01/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/teamProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>memberjoin2</title>\r\n");
      out.write("<style>\r\n");
      out.write("\tinput[type=\"password\"], input[type=\"text\"]{all: unset;}\r\n");
      out.write("</style>\r\n");
      out.write("<style>\r\n");
      out.write("\t.icons li a{\r\n");
      out.write("\t\tall: unset;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("<style>\r\n");
      out.write("\tp{\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"resources/assets/css/main.css\" />\r\n");
      out.write("\t<script src=\"//code.jquery.com/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"wrapper\" class=\"fade-in\">\r\n");
      out.write("\t<!-- 헤더 -->\r\n");
      out.write("\t\t<header id=\"header\">\r\n");
      out.write("\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\" class=\"logo\">맛.ZIP</a>\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- 상단 바 -->\r\n");
      out.write("\t\t<nav id=\"nav\">\r\n");
      out.write("\t\t\t<ul class=\"links\">\t\t\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\">메인페이지</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/storemain\">맛집</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/community\">커뮤니티</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t<div id=\"main\">\r\n");
      out.write("\r\n");
      out.write("\t<form action=\"memberJoin2\" method=\"post\">\r\n");
      out.write("\t<table>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>ID</th>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<td><div class=\"row gtr-uniform\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-6 col-12-xsmall\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"userid\" placeholder=\"ID\" required id=\"demo-name\"/>\r\n");
      out.write("\t\t\t\t\t</div></div>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>패스워드</th>\r\n");
      out.write("<!-- \t\t\t<td><input width=\"300px;\" name=\"userpw\" type=\"password\" placeholder=\"PW\" required></td> -->\r\n");
      out.write("\t\t\t<td><div class=\"row gtr-uniform\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-6 col-12-xsmall\">\r\n");
      out.write("\t\t\t\t\t\t<input name=\"userpw\" type=\"password\" placeholder=\"PW\" required id=\"demo-name\"/>\r\n");
      out.write("\t\t\t\t\t</div></div>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>패스워드 확인</th>\r\n");
      out.write("<!-- \t\t\t<td><input name=\"confirmpw\" type=\"password\" placeholder=\"PW확인\" required></td> -->\r\n");
      out.write("\t\t\t<td><div class=\"row gtr-uniform\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-6 col-12-xsmall\">\r\n");
      out.write("\t\t\t\t\t\t<input name=\"confirmpw\" type=\"password\" placeholder=\"PW확인\" required id=\"demo-name\"/>\r\n");
      out.write("\t\t\t\t\t</div></div>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${membertype == 'gemember' ? \"이름\":\"가게 이름\"}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</th>\r\n");
      out.write("<!-- \t\t\t<td><input name=\"username\" placeholder=\"OOO\" required></td> -->\r\n");
      out.write("\t\t\t<td><div class=\"row gtr-uniform\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-6 col-12-xsmall\">\r\n");
      out.write("\t\t\t\t\t\t<input name=\"username\" placeholder=\"OOO\" required type=\"text\" id=\"demo-name\"/>\r\n");
      out.write("\t\t\t\t</div></div>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>성별</th>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t<div class=\"col-6 col-12-small\">\r\n");
      out.write("\t\t\t\t<input type=\"radio\" id=\"gender1\" name=\"gender\" value=\"여자\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.gender eq '여자' ? \"checked\" : \"\"}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" required>\r\n");
      out.write("\t\t\t\t<label for=\"gender1\">여자</label> &nbsp;\r\n");
      out.write("\t\t\t\t<input type=\"radio\" id=\"gender2\" name=\"gender\" value=\"남자\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.gender eq '남자' ? \"checked\" : \"\"}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" required>\r\n");
      out.write("\t\t\t\t<label for=\"gender2\">남자</label>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>이메일</th>\r\n");
      out.write("<!-- \t\t\t<td><input name=\"email\" placeholder=\"hello@hello.com\" required></td> -->\r\n");
      out.write("\t\t\t<td><div class=\"row gtr-uniform\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-6 col-12-xsmall\">\r\n");
      out.write("\t\t\t\t\t\t<input name=\"email\" placeholder=\"hello@hello.com\" required type=\"text\" id=\"demo-name\"/>\r\n");
      out.write("\t\t\t\t</div></div>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>전화번호</th>\r\n");
      out.write("<!-- \t\t\t<td><input name=\"phone\" placeholder=\"010-1234-5678\" required></td> -->\r\n");
      out.write("\t\t\t<td><div class=\"row gtr-uniform\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-6 col-12-xsmall\">\r\n");
      out.write("\t\t\t\t\t\t<input name=\"phone\" placeholder=\"010-1234-5678\" required type=\"text\" id=\"demo-name\"/>\r\n");
      out.write("\t\t\t\t</div></div>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"membertype\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${membertype }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t<p><input type=\"submit\" value=\"가입\"></p>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t\t<div id=\"copyright\">\r\n");
      out.write("\t\t\t<ul><li>&copy; </li></ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("</div></div>\r\n");
      out.write("<input id=\"user\" type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.userid }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t<script src=\"resources/assets/js/jquery.min.js?ver=2\"></script>\r\n");
      out.write("\t\t<script src=\"resources/assets/js/jquery.scrollex.min.js?ver=3\"></script>\r\n");
      out.write("\t\t<script src=\"resources/assets/js/jquery.scrolly.min.js?ver=4\"></script>\r\n");
      out.write("\t\t<script src=\"resources/assets/js/browser.min.js?ver=5\"></script>\r\n");
      out.write("\t\t<script src=\"resources/assets/js/breakpoints.min.js?ver=6\"></script>\r\n");
      out.write("\t\t<script src=\"resources/assets/js/util.js?ver=7\"></script>\r\n");
      out.write("\t\t<script src=\"resources/assets/js/main.js?ver=8\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
